# Generated by Django 5.1.7 on 2025-09-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='after_photo',
            field=models.ImageField(blank=True, null=True, upload_to='task_photos/after/'),
        ),
        migrations.AddField(
            model_name='task',
            name='before_photo',
            field=models.ImageField(blank=True, null=True, upload_to='task_photos/before/'),
        ),
    ]
