# Generated by Django 5.1.7 on 2025-09-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_task_after_photo_task_before_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_photo',
            field=models.ImageField(blank=True, null=True, upload_to='tasks/photos/'),
        ),
    ]
