# Generated by Django 5.1.7 on 2025-09-23 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_task_task_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_code',
        ),
    ]
