# Generated by Django 5.1.7 on 2025-09-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_task_task_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
