# Generated by Django 5.1.7 on 2025-09-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_task_task_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='materials_used',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='work_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
