# Generated by Django 5.1.7 on 2025-09-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_task_additional_notes_task_materials_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='pending_reason',
            field=models.TextField(blank=True, help_text='Reason for pending', null=True),
        ),
    ]
