# Generated by Django 5.1.7 on 2025-10-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_task_pending_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_progress', 'In_Progress'), ('completed', 'Completed')], default='new', max_length=20),
        ),
    ]
