# Generated by Django 5.1.7 on 2025-10-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_task_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reopen_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
