# Generated by Django 5.1.7 on 2025-10-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_task_reopen_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_reopened',
            field=models.BooleanField(default=False),
        ),
    ]
